# Generated by Django 3.1.5 on 2021-01-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(upload_to='event_images/%Y/%m/%d/'),
        ),
    ]
